services:
  episodely:
    image: ghcr.io/keenfann/episodely:latest
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_PATH: /data/episodely.sqlite
    volumes:
      - ./data:/data
